services:
  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    image: postgres:17.0
    container_name: cloud-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud-app
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
