apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.0
          ports:
            - containerPort: 5432
              name: 'postgres'
          env:
            - name: POSTGRES_DB
              value: cloud-app
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
